### ISSUE TITLE
Game crash: main.lua line 144" tried to index a nil value "selected".

### ISSUE THREAD

**Issue by MIfeanyi** [Mandarancio/Planetary-Ballistics#1]
When I tried to play the game I got this error after losing.

**Comment by MIfeanyi** [comment]
I think I might have identified the issue. In`main.lua` lines: 163-181, the nil check should cover this whole block of code since it's required by all other checks and comparisons. Also `if player.selected~= nil and player.selected.rockets>0 then` will crash if `player.selected = nil` because LUA will still go on to index selected to compare `selected.rockets >0 --line177/8`.

**Comment by MIfeanyi** [comment]
I could be missing something so please let me know. I dont know what to do after I die haha. I will do a pull request.

**Comment by MIfeanyi** [comment]
seems like major code was added after I did this. Hopefully that commit can help fix the issue.

**Comment by Mandarancio** [comment]
Thank you very much for the bug report, it should be fixed in the current code :+1:

**Comment by MIfeanyi** [comment]
Closing
